import turtle
turtle.speed(10)
turtle.setheading(0)
# hexagon
turtle.penup()
turtle.color("yellow")
turtle.goto(0,200)
turtle.pensize(4)
turtle.pendown()
turtle.circle(-80, 360, 6)

turtle.penup()
turtle.color("blue")
turtle.goto(0,200)
turtle.pensize(4)
turtle.pendown()
turtle.circle(80, 360, 6)

turtle.penup()
turtle.color("red")
turtle.goto(0,200)
turtle.pensize(4)
turtle.seth(90)
turtle.pendown()
turtle.circle(80, 360, 6)

turtle.penup()
turtle.color("green")
turtle.goto(0,200)
turtle.pensize(4)
turtle.seth(-90)
turtle.pendown()
turtle.circle(80, 360, 6)


# Traffic light
turtle.penup()
turtle.color("yellow")
turtle.fillcolor("yellow")
turtle.goto(100, -200)
turtle.seth(90)
turtle.pendown()
turtle.begin_fill()
turtle.circle(200, 360, 4)
turtle.end_fill()

turtle.penup()
turtle.color("black")
turtle.goto(90, -200)
turtle.seth(90)
turtle.pendown()
turtle.circle(190, 360, 4)

turtle.penup()
turtle.color("black")
turtle.fillcolor("black")
turtle.goto(-70, -100)
turtle.seth(180)
turtle.pendown()
turtle.begin_fill()
turtle.fd(60)
turtle.seth(-90)
turtle.fd(180)
turtle.seth(360)
turtle.fd(60)
turtle.seth(90)
turtle.fd(180)
turtle.end_fill()

turtle.penup()
turtle.color("red")
turtle.fillcolor("red")
turtle.goto(-76, -130)
turtle.pendown()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()

turtle.penup()
turtle.color("yellow")
turtle.fillcolor("yellow")
turtle.goto(-76, -190)
turtle.pendown()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()

turtle.penup()
turtle.color("green")
turtle.fillcolor("green")
turtle.goto(-76, -250)
turtle.pendown()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()

turtle.done()